Better effort with ARCHFLAGS
The previous patch was incredibly sloppy.  Didn't have my brain engaged.
This one solves the issue a little more cleanly.  Still may not be
completely perfect for some environments that remove the name clang,
but still have clang as cc.  But this gets it pretty close.

diff --git a/src/tools/xddprof/xddprof.in b/src/tools/xddprof/xddprof.in
--- a/src/tools/xddprof/xddprof.in
+++ b/src/tools/xddprof/xddprof.in
@@ -40,6 +40,13 @@ XDDPROF_PY_SRC="${XDD_SITE_PACKAGES}/xdd_storage_profile.py"
 #
 # Should probably make sure everything exists
 #
-${PYTHON_EXE} ${XDDPROF_PY_SRC} ${@}
+if [ -r "${XDDPROF_PY_SRC}" ]; then
+    ${PYTHON_EXE} ${XDDPROF_PY_SRC} ${@}
+    rc=$?
+else
+    echo "${XDDPROF_PY_SRC}: file not found"
+    rc=1
+fi
 
+exit $rc
 
